export const actionTypes = {
    GET_ALL_CONTACTS: 'GET_ALL_CONTACTS',
    GET_CONTACT: 'GET_CONTACT',
    CREATE_CONTACT: 'CREATE_CONTACT',
    DELETE_CONTACT: 'DELETE_CONTACT',
    DELETE_EMAIL: 'DELETE_EMAIL',
    ADD_EMAIL: 'ADD_EMAIL',
    UPDATE_NAME: 'UPDATE_NAME',
    SELECT_CONTACT: 'SELECT_CONTACT'
};