export const actionTypes = {
    RESET_FORM: 'RESET_FORM',
    GET_ALL_CONTACTS: 'GET_ALL_CONTACTS',
    GET_CONTACT: 'GET_CONTACT',
    CREATE_CONTACT: 'CREATE_CONTACT',
    DELETE_CONTACT: 'DELETE_CONTACT',
    DELETE_EMAIL: 'DELETE_EMAIL',
    ADD_EMAIL: 'ADD_EMAIL',
    UPDATE_NAME: 'UPDATE_NAME',
    SELECT_CONTACT: 'SELECT_CONTACT',
    FETCH_ALL_CONTACTS: 'FETCH_ALL_CONTACTS',
    SET_FIRST_NAME: 'SET_FIRST_NAME',
    SET_LAST_NAME: 'SET_LAST_NAME',
    SET_EMAIL: 'SET_EMAIL',
    SHOW_EMAIL_INPUT: 'SHOW_EMAIL_INPUT',
    CLEAR_NEW_EMAIL_INPUT: 'CLEAR_NEW_EMAIL_INPUT',
    UPDATE_APP_CONTACTS: 'UPDATE_APP_CONTACTS',
    GET_INITIAL_STATE: 'GET_INITIAL_STATE'
};